---
upload_path: "/_site/:year:/:month:/:day:"
frontmatter_file_url_template: "/_site/:year:/:month:/:day:"
body_file_url_template: "/_site/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: https://github.com/designucsd/designucsd.github.io/settings/hooks/16635770
collections: 
