---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: ''
collections: 
upload_dir: _site
public_path: "/_site"
front_matter_path: "/_site"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
